// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/jones/work/cosmics/LArSoft-v08_50_00/work/scripts/rhiAna/srcs/EventProcessor.h;
#pragma link C++ defined_in "/home/jones/work/cosmics/LArSoft-v08_50_00/work/scripts/rhiAna/srcs/EventProcessor.cpp";

#endif
